### ISSUE TITLE
Header problems

### ISSUE THREAD

**Issue by hoha666** [hoha666/GothamAutoRenov#4]
Within current version, I face 3 problems in header section of homepage, please solve them :
1 - picture not loaded
2 - picture not loaded
3 - there should be a gap or margin top around 5 to 10 px from top
please check the picture
![e1](https://user-images.githubusercontent.com/17946462/233606611-495b13d8-c188-4b42-843f-43ce9431822a.jpg)

**Comment by ramindev61** [comment]
Hello,  Git push did not work and sent this message:
{$ git push  https://github.com/hoha666/GothamAutoRenov.git
Enumerating objects: 5, done.
Counting objects: 100% (5/5), done.
Delta compression using up to 4 threads
Compressing objects: 100% (3/3), done.
Writing objects: 100% (3/3), 344 bytes | 344.00 KiB/s, done.
Total 3 (delta 2), reused 0 (delta 0), pack-reused 0
remote: Resolving deltas: 100% (2/2), completed with 2 local objects.
remote: error: GH006: Protected branch update failed for refs/heads/main.
remote: error: At least 1 approving review is required by reviewers with write access.
To https://github.com/hoha666/GothamAutoRenov.git
 ! [remote rejected] main -> main (protected branch hook declined)
error: failed to push some refs to 'https://github.com/hoha666/GothamAutoRenov.git'}
